"""real init expenses and repayments

Revision ID: 1a49bf01f991
Revises: 6e0aaebe216c
Create Date: 2026-05-19 21:36:24.214090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a49bf01f991'
down_revision: Union[str, Sequence[str], None] = '6e0aaebe216c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('expense_type', sa.Enum('FOOD', 'DECORATION', 'TRANSPORT', 'OTHER', name='expense_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIALLY_REPAID', 'FULLY_REPAID', name='expense_status'), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payer_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_to_pay', sa.Float(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('debtor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='repayment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['debtor_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repayments_id'), 'repayments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repayments_id'), table_name='repayments')
    op.drop_table('repayments')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
