"""repayment and expense integration

Revision ID: bf52a1562242
Revises: 1a49bf01f991
Create Date: 2026-09-08 13:36:59.285001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf52a1562242'
down_revision: Union[str, Sequence[str], None] = '1a49bf01f991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repayments', 'expense_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repayments', 'expense_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
